trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
    - job: build
      displayName: build
        
      steps:
      - task: ShellScript@2
        inputs:
          scriptPath: '$(Build.SourcesDirectory)/tools/depends/bootstrap'
          workingDirectory: '$(Build.SourcesDirectory)/tools/depends'
        
      - task: ShellScript@2
        inputs:
          scriptPath: '$(Build.SourcesDirectory)/tools/depends/configure'
          args: '--with-tarballs=$HOME/android-tools/xbmc-tarballs --host=aarch64-linux-android --with-sdk-path=$HOME/android-tools/android-sdk-linux --with-ndk-path=$HOME/android-tools/android-ndk-r21e --prefix=$HOME/android-tools/xbmc-depends'
          workingDirectory: '$(Build.SourcesDirectory)/tools/depends'
        
      - task: CMake@1
        inputs:
          workingDirectory: '$(Build.SourcesDirectory)/tools/depends'
          cmakeArgs: '-j$(getconf _NPROCESSORS_ONLN)'
