trigger:
- main
- feature/*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
    - job: build
      displayName: build
        
      steps:
      - bash: env
        displayName: env vars

      - bash: echo "##vso[task.setvariable variable=ANDROID_HOME;]$ANDROID_HOME"
      - bash: echo "##vso[task.setvariable variable=ANDROID_NDK;]$ANDROID_NDK_LATEST_HOME"

      - script: 'mkdir android-tools'
        workingDirectory: '$(Build.ArtifactStagingDirectory)'

      - task: ShellScript@2
        inputs:
          scriptPath: '$(Build.SourcesDirectory)/tools/depends/bootstrap'
          workingDirectory: '$(Build.SourcesDirectory)/tools/depends/'
        
      - task: ShellScript@2
        inputs:
          scriptPath: '$(Build.SourcesDirectory)/tools/depends/configure'
          args: '--with-tarballs=$(Build.ArtifactStagingDirectory)/android-tools/xbmc-tarballs --host=aarch64-linux-android --with-sdk-path=$(ANDROID_HOME) --with-ndk-path=$(ANDROID_NDK) --prefix=$(Build.ArtifactStagingDirectory)/android-tools/xbmc-depends'
          workingDirectory: '$(Build.SourcesDirectory)/tools/depends/'
        
      - script: 'make -j$(getconf _NPROCESSORS_ONLN)'
        workingDirectory: '$(Build.SourcesDirectory)/tools/depends/'

      - script: 'make -j$(getconf _NPROCESSORS_ONLN) -C tools/depends/target/binary-addons'  
        workingDirectory: '$(Build.SourcesDirectory)/'

      - script: 'make -C tools/depends/target/cmakebuildsys'  
        workingDirectory: '$(Build.SourcesDirectory)/'

      - script: 'make -j$(getconf _NPROCESSORS_ONLN)'  
        workingDirectory: '$(Build.SourcesDirectory)/'
